// <auto-generated />
using DiscordBot.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace gmodwatcher.Migrations
{
    [DbContext(typeof(BotContext))]
    [Migration("20201130074232_LastCommitKey")]
    partial class LastCommitKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DiscordBot.Models.LastestCommit", b =>
                {
                    b.Property<int>("LastCommit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("LastCommit");

                    b.ToTable("LastCommit");
                });

            modelBuilder.Entity("DiscordBot.Models.RegisteredChannel", b =>
                {
                    b.Property<ulong>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChannelId");

                    b.ToTable("Channels");
                });
#pragma warning restore 612, 618
        }
    }
}
